language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r tests/requirements.txt
  - pip install pycparser==2.18
  - pip install idna==2.6
  - pip install coveralls==1.2.0
script: 
  - coverage run --source . setup.py nosetests 
after_success:
    coveralls
