# Max number of attempts used for task run-time, each attempt is separated by 30s
attempt_limit: 80

# aws profile
profile_name: 'default'

# Docker container configs
container_memory: 1024
container_cpu: 1024
container_image: 'dandb/salt_review:2015-8-7'

# Logfile configs
save_logs: True
highstate_log_dir: highstate_logs
